language: node_js
node_js:
    - '8.6.0'
before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
before_script:
    - npm install
script:
    - npm run test
    - npm run build
cache:
    directories:
        - 'node_modules'
